### PR TITLE
Scale the mask to match the scaled image when using mask shrink with flux fill

### PR DESCRIPTION
**Pull request by willhsmit**
To fully fix https://github.com/mcmonkeyprojects/SwarmUI/issues/439, I think the mask also needs to be scaled before passing into the conditioning function.

I wasn't able to find an existing scaled copy of the mask, or an equivalent to SwarmImageScaleForMP that works on masks, so there's some repeated code here. There may be a better way of reusing SwarmImageScaleForMP or work that's already been done scaling the image.

### CODE REVIEW

**Comment by willhsmit** [comment]
With this, I get fairly good results for the example in https://github.com/mcmonkeyprojects/SwarmUI/issues/439:

1807-Man with jacket-flux1-fill-dev-Q4_K_S-2003358640

**Comment by mcmonkey4eva** [comment]
Valid identification of where the problem was, wrong solution to it though -- it just needed to be the CroppedMask instead of the full mask.

**Comment by willhsmit** [comment]
Huh. I swear I tried doing that first. 

Results are exactly as I expected now. Thanks!

**Comment by FurkanGozukara** [comment]
awesome so i am assuming something fixed :D 

do we have example?

**Comment by willhsmit** [comment]
This was for https://github.com/mcmonkeyprojects/SwarmUI/issues/439 but was rejected in favor of a better fix https://github.com/mcmonkeyprojects/SwarmUI/commit/5e303de2f58b36ae1d5d775caf60dfe0a3687677. 

439 has reproduction steps for an example of what was going wrong, I commented on 439 with what the reproduction steps give me after the latest fix.

Mask Shrink Grow's a feature that you've probably used a long time on other models anyway, but a more realistic demo of how to use 'Mask shrink grow' with Flux fill would probably be:
(1) generate a 1024x1024 photorealistic or anime picture with a character using non-fill flux schnell/dev
(2) you are generally happy with your gen, but some detail like a hand is a mess
(3) you mask the hand to fix it with an inpainting model like Flux fill. Maybe the masked area ends up being like 50 pixels square
(4) Generating with the whole image as a canvas for inpainting continues to struggle to get the fine detail right in the 50x50 hand area.
(5) Using 'Mask shrink grow', find a grow value that is large enough that the Flux fill can access surrounding context to place the hand correctly, but small enough that the hand takes up more of the image and Flux fill can focus more on the detail. For example, a grow value of 96 with a 50x50 mask means the UI is scaling a ~242x242 space up to 1024x1024, growing your 50x50 mask into a ~200x200 area that gives the details more focus, before shrinking and recompositing again.
(6) Generate and hopefully get a better hand.

Side comments:
(1) Particularly useful if the original image wasn't 1024px; if it's much smaller the model will struggle even harder to get small details right without using 'Mask shrink grow' to zoom in; if it's much bigger, it will take a lot of time and VRAM to use a full 3000+ image as the canvas just to infill a small part of it unless you use 'Mask shrink grow'.
(2) A hack alternative to tuning the 'Mask shrink grow' value carefully is to set it to a very low value, and then add little extra outlying pixel-sized dots to your mask to define exactly where you want the boundaries of the canvas rectangle to be.

**Comment by FurkanGozukara** [comment]
@willhsmit so this is generating masked area in bigger resolution and then automatically shrinking back into that small area basically copy pasting right?

excellent

**Pull request closed without merging**
