### PR TITLE
Update extension_list.fds

### PR DESCRIPTION
**Pull request by Urabewe**
Added info for OllamaVision let me know if it needs fixing or anything.

### CODE REVIEW

**Comment by mcmonkey4eva** [comment]
This extension has a lot of custom CSS, ideally you'd try as best as possible to match the general style of Swarm and the user's currently selected Theme, and only deviate where the existing Swarm styleset doesn't cover an interaction well.
If you think Swarm's styling can be improved, I'd suggest PRing css updates to Swarm itself, or a new theme.

I've pushed an update to the Extension guidelines to suggest this.

**Comment by Urabewe** [comment]
Okay, I will work on changing the style to match the user settings in SwarmUI instead.

**Comment by Urabewe** [comment]
I got the theme correct and all functionality intact. The extension will now take on all the theming of swarm ui. The only thing I left the same was the status bar at the bottom of the extension for easy visibility of whats going on.

**Comment by kwal559** [comment]
hi urabewe, i've taken the time to try a lot of caption models.  There is an image tagger app called Taggui that offers way too many options and I tested many of them.  Keep in mind some 'vision' models only look at the filename and maybe metadata, they spice up the text and respond without ever having processed an image.  If you are looking for other models to support or consider, a list is below.
MiaoshouAI/Florence-2-base-PromptGen  -  has been my favorite so far .. even forcing extra tokens with caption_more_details, it's fast. i use min 5 max 110 tokens and it averages a good sized paragraph in half a second per image - without getting too 'inner dialogue' heavy (a text-to-image model doesn't care if you 'are reminded of grandmothers gingerbread cookies from christmas past', or, adds elements not intended)

these range in size heavily, couple hundred KB -> 10+ GB.. Some censor a lot more than others..

`'internlm/internlm-xcomposer2-vl-7b-4bit',
    'internlm/internlm-xcomposer2-vl-7b',
    'internlm/internlm-xcomposer2-vl-1_8b',
    'internlm/internlm-xcomposer2-4khd-7b',
    'THUDM/cogvlm-chat-hf',
    'THUDM/cogagent-vqa-hf',
    'THUDM/cogvlm2-llama3-chat-19B-int4',
    'THUDM/cogvlm2-llama3-chat-19B',
    'microsoft/Florence-2-large-ft',
    'microsoft/Florence-2-large',
    'microsoft/Florence-2-base-ft',
    'microsoft/Florence-2-base',
    'MiaoshouAI/Florence-2-base-PromptGen',
    'microsoft/Phi-3-vision-128k-instruct',
    'llava-hf/llava-v1.6-mistral-7b-hf',
    'llava-hf/llava-v1.6-vicuna-7b-hf',
    'llava-hf/llava-v1.6-vicuna-13b-hf',
    'llava-hf/llava-v1.6-34b-hf',
    'xtuner/llava-llama-3-8b-v1_1-transformers',
    'vikhyatk/moondream2',
    'vikhyatk/moondream1',
    'SmilingWolf/wd-vit-large-tagger-v3',
    'SmilingWolf/wd-swinv2-tagger-v3',
    'SmilingWolf/wd-convnext-tagger-v3',
    'SmilingWolf/wd-vit-tagger-v3',
    'SmilingWolf/wd-v1-4-moat-tagger-v2',
    'SmilingWolf/wd-v1-4-swinv2-tagger-v2',
    'SmilingWolf/wd-v1-4-convnext-tagger-v2',
    'SmilingWolf/wd-v1-4-convnextv2-tagger-v2',
    'SmilingWolf/wd-v1-4-vit-tagger-v2',
    'llava-hf/llava-1.5-7b-hf',
    'llava-hf/llava-1.5-13b-hf',
    'llava-hf/bakLlava-v1-hf',
    'Salesforce/instructblip-vicuna-7b',
    'Salesforce/instructblip-vicuna-13b',
    'Salesforce/instructblip-flan-t5-xl',
    'Salesforce/instructblip-flan-t5-xxl',
    'Salesforce/blip2-opt-2.7b',
    'Salesforce/blip2-opt-6.7b',
    'Salesforce/blip2-opt-6.7b-coco',
    'Salesforce/blip2-flan-t5-xl',
    'Salesforce/blip2-flan-t5-xxl',
    'microsoft/kosmos-2-patch14-224

**Comment by southbayjay** [comment]
@Urabewe Is this good to go?

**Comment by mcmonkey4eva** [comment]
btw the C# code's handling of JSON seems wonked a bit.
The `BackendSchema.cs` class isn't used and isn't valid, can probably just be deleted.
Within the API class, there's a lot of manual JSON wrangling, but Swarm has built in helpers for this stuff, eg instead of `PostAsync` with manual json wrangling, you can just `PostJson` and it does the same inside but with much simpler code, since it handles the json inside the util method

**Comment by mcmonkey4eva** [comment]
oh also i'd recommend switching to the MIT license unless you have a particular reason to prefer the GPL.

**Pull request merged**
